# This is a basic workflow to help you get started with Actions

name: CI Stripe Connect Account Reciever

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    environment: testing

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Prepare runner with ssh keys
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DOKKU_HOST: ${{ secrets.DOKKU_HOST }}
        run: |
          set -x
          mkdir -p ~/.ssh
          eval `ssh-agent -s`
          ssh-add - <<< "$SSH_PRIVATE_KEY"
          ssh-keyscan $DOKKU_HOST >> ~/.ssh/known_hosts
          
      - name: Create dokku app if dosent already exist using dokku apps:create
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DOKKU_HOST: ${{ secrets.DOKKU_HOST }}
        run: |
          set -x
          eval `ssh-agent -s`
          ssh-add - <<< "$SSH_PRIVATE_KEY"
          echo Creating dokku app testing-stripe-connect-account-reciever
          ssh dokku@$DOKKU_HOST -C "dokku apps:create testing-stripe-connect-account-reciever" | true
          echo The url will be testing-stripe-connect-account-reciever.pcpink.co.uk
          ssh dokku@$DOKKU_HOST -C "dokku git:initialize testing-stripe-connect-account-reciever"
          ssh dokku@$DOKKU_HOST -C "dokku config:set --no-restart testing-stripe-connect-account-reciever PORT=${{ secrets.PORT }} HOSTNAME=${{ secrets.HOSTNAME }}"
          ssh dokku@$DOKKU_HOST -C "dokku config:set --no-restart testing-stripe-connect-account-reciever REDIS_HOSTNAME=${{ secrets.REDIS_HOSTNAME }} REDIS_PORT=${{ secrets.REDIS_PORT }}"
          ssh dokku@$DOKKU_HOST -C "dokku config:set --no-restart testing-stripe-connect-account-reciever REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}"
          
      - id: deploy
        name: Deploy to dokku
        uses: idoberko2/dokku-deploy-github-action@v1
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            dokku-host: ${{ secrets.DOKKU_HOST }}
            app-name: 'testing-stripe-connect-account-reciever'
            git-push-flags: --force 

