name: Prod Stripe Connect Account Announcer

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-prod:
    name: Deploy prod Stripe Connect Account Announcer
    runs-on: ubuntu-20.04
    environment: prod

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Prepare runner with ssh keys
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DOKKU_HOST: ${{ secrets.DOKKU_HOST }}
        run: |
          set -x
          mkdir -p ~/.ssh
          eval `ssh-agent -s`
          ssh-add - <<< "$SSH_PRIVATE_KEY"
          ssh-keyscan $DOKKU_HOST >> ~/.ssh/known_hosts
          
      - name: Create dokku app if dosent already exist using dokku apps:create
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DOKKU_HOST: ${{ secrets.DOKKU_HOST }}
        run: |
          set -x
          eval `ssh-agent -s`
          ssh-add - <<< "$SSH_PRIVATE_KEY"
          echo Creating dokku app prod-stripe-connect-account-announcer
          ssh dokku@$DOKKU_HOST -C "dokku apps:create prod-stripe-connect-account-announcer" | true
          echo The url will be prod-stripe-connect-account-announcer.pcpink.co.uk
          ssh dokku@$DOKKU_HOST -C "dokku git:initialize prod-stripe-connect-account-announcer"
          ssh dokku@$DOKKU_HOST -C "dokku config:set --no-restart prod-stripe-connect-account-announcer DENO_PORT=${{ secrets.DENO_PORT }} HOSTNAME=${{ secrets.HOSTNAME }}"
          ssh dokku@$DOKKU_HOST -C "dokku config:set --no-restart prod-stripe-connect-account-announcer BIND_ADDRESS=${{ secrets.BIND_ADDRESS }}"
          ssh dokku@$DOKKU_HOST -C "dokku config:set --no-restart prod-stripe-connect-account-announcer REDIS_HOSTNAME=${{ secrets.REDIS_HOSTNAME }} REDIS_PORT=${{ secrets.REDIS_PORT }}"
          ssh dokku@$DOKKU_HOST -C "dokku config:set --no-restart prod-stripe-connect-account-announcer REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}"
          ssh dokku@$DOKKU_HOST -C "dokku ps:set testing-stripe-connect-account-announcer restart-policy unless-stopped"
          ssh dokku@$DOKKU_HOST -C "dokku ps:rebuild prod-stripe-connect-account-announcer"
          
      - id: deploy
        name: Deploy to dokku
        uses: idoberko2/dokku-deploy-github-action@v1
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            dokku-host: ${{ secrets.DOKKU_HOST }}
            app-name: 'prod-stripe-connect-account-announcer'
            git-push-flags: --force

      - id: smoke-test
        name: Smoke test
        run: |
          set -x
          curl -v -H 'Content-Type: application/json' -d '{}' prod-stripe-connect-account-announcer.pcpink.co.uk:8001| grep 'Stripe connect account added or updated'

